tourandtravel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path("",include("tourandtravelapp.urls")),
    path('summernote/', include('django_summernote.urls')),
    
]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourandtravelapp/urls.py
from django.urls import path
from .views import *

app_name="tourandtravelapp"
urlpatterns = [
# for client urls
	path("",HomeView.as_view(),name="home"),
    path('about/', AboutView.as_view(), name='about'),
    path('service/', ServiceView.as_view(), name='service'),
    path('package/', PackageView.as_view(), name='package'),
    path('contact/', ContactView.as_view(), name='contact'),
    path("subscriber/", SubscriberCreateView.as_view(), name="subscriber"),
    path('package/', PackageView.as_view(), name='package'),
	path('offer/<int:pk>/detail/',
		OfferDetailView.as_view(), name="offerdetail"),
	path('package/<int:pk>/detail/',
         PackageDetailView.as_view(), name="packagedetail"),
	path("service-package/<int:pk>/book/",
         ClientPackageBookView.as_view(), name='clientpackagebook'),
	path('enquery/', EnqueryView.as_view(), name='enquery'),
	path("ajax/service-packages/",
		AjaxGetPackagesView.as_view(), name='ajaxgetpackages'),
	path('package/<int:pk>/comment/',
         PackageCommentView.as_view(), name="packagecomment"),
	path('album/', AlbumView.as_view(), name='album'),
	path('service/<slug:slug>/detail/',
         ServiceDetailView.as_view(), name="servicedetail"),

	# foradmin
	path('signin/', SigninView.as_view(), name='signin'),
    path('signout/', SignoutView.as_view(), name='signout'),
    path('med-admin/home', AdminHomeView.as_view(), name='adminhome'),

    # for adding destination,delete update
    path('med-admin/service/list/',
    	AdminServiceListView.as_view(), name="adminservicelist"),
	path('med-admin/service/create/',
         AdminServiceCreateView.as_view(), name="adminservicecreate"),
	path('med-admin/<int:pk>/edit/',
         AdminServiceUpdateView.as_view(), name="adminserviceupdate"),
    path('med-admin/<int:pk>/delete/',
         AdminServiceDeleteView.as_view(), name="adminservicedelete"),

# forservice package
path('med-admin/servicepackage/list/',
         AdminServicePackageListView.as_view(), name="adminservicepackagelist"),
path('med-admin/servicepackage/create/',
         AdminServicePackageCreateView.as_view(), name="adminservicepackagecreate"),
path('med-admin/<int:pk>/packageedit/',
         AdminServicePackageUpdateView.as_view(), name="adminservicepackageupdate"),
path('med-admin/<int:pk>/packagedelete/',
         AdminServicePackageDeleteView.as_view(), name="adminservicepackagedelete"),

# for team
path('med-admin/team/list/',
         AdminTeamListView.as_view(), name="adminteamlist"),
path('med-admin/team/create/',
         AdminTeamCreateView.as_view(), name="adminteamcreate"),
path('med-admin/<int:pk>/teamedit/',
         AdminTeamUpdateView.as_view(), name="adminteamupdate"),
path('med-admin/<int:pk>/teamdelete/',
         AdminTeamDeleteView.as_view(), name="adminteamdelete"),

# for offer
path('med-admin/offer/list/',
         AdminOfferListView.as_view(), name="adminofferlist"),
path('med-admin/offer/create/',
         AdminOfferCreateView.as_view(), name="adminoffercreate"),
path('med-admin/<int:pk>/offeredit/',
         AdminOfferUpdateView.as_view(), name="adminofferupdate"),
path('med-admin/<int:pk>/offerdelete/',
         AdminOfferDeleteView.as_view(), name="adminofferdelete"),

# for subscriber
path('med-admin/subscriber/list/',
         AdminSubscriberListView.as_view(), name="adminsubscriberlist"),
path('med-admin/subscriber/create/',
         AdminSubscriberCreateView.as_view(), name="adminsubscribercreate"),
path('med-admin/<int:pk>/subscriberedit/',
         AdminSubscriberUpdateView.as_view(), name="adminsubscriberupdate"),
path('med-admin/<int:pk>/subscriberdelete/',
         AdminSubscriberDeleteView.as_view(), name="adminsubscriberdelete"),

# for testimonial
path('med-admin/testimonial/list/',
         AdminTestimonialListView.as_view(), name="admintestimoniallist"),
    path('med-admin/testimonial/create/',
         AdminTestimonialCreateView.as_view(), name="admintestimonialcreate"),
    path('med-admin/<int:pk>/testimonialedit/',
         AdminTestimonialUpdateView.as_view(), name="admintestimonialupdate"),
    path('med-admin/<int:pk>testimonialdelete/',
         AdminTestimonialDeleteView.as_view(), name="admintestimonialdelete"),

# for album
path('med-admin/album/list/',
         AdminAlbumListView.as_view(), name="adminalbumlist"),
path('med-admin/album/create/',
         AdminAlbumCreateView.as_view(), name="adminalbumcreate"),
path('med-admin/<int:pk>/albumedit/',
         AdminAlbumUpdateView.as_view(), name="adminalbumupdate"),
path('med-admin/<int:pk>albumdelete/',
         AdminAlbumDeleteView.as_view(), name="adminalbumdelete"),       

         # for image

path('med-admin/image/list/',
         AdminImageListView.as_view(), name="adminimagelist"),
path('med-admin/image/create/',
         AdminImageCreateView.as_view(), name="adminimagecreate"),
path('med-admin/<int:pk>/imageedit/',
         AdminImageUpdateView.as_view(), name="adminimageupdate"),
path('med-admin/<int:pk>imagedelete/',
         AdminImageDeleteView.as_view(), name="adminimagedelete"), 

# for video
path('med-admin/video/list/',
         AdminVideoListView.as_view(), name="adminvideolist"),
path('med-admin/video/create/',
         AdminVideoCreateView.as_view(), name="adminvideocreate"),
path('med-admin/<int:pk>/videoedit/',
         AdminVideoUpdateView.as_view(), name="adminvideoupdate"),
path('med-admin/<int:pk>videodelete/',
         AdminVideoDeleteView.as_view(), name="adminvideodelete"),
# for enqury
path('med-admin/enquery/list/',
         AdminEnqueryListView.as_view(), name="adminenquerylist"),
path('med-admin/enquery/create/',
         AdminEnqueryCreateView.as_view(), name="adminenquerycreate"),
path('med-admin/<int:pk>/enqueryedit/',
         AdminEnqueryUpdateView.as_view(), name="adminenqueryupdate"),
path('med-admin/<int:pk>enquerydelete/',
         AdminEnqueryDeleteView.as_view(), name="adminenquerydelete"),

# formessage
path('med-admin/message/list/',
         AdminMessageListView.as_view(), name="adminmessagelist"),
path('med-admin/message/create/',
         AdminMessageCreateView.as_view(), name="adminmessagecreate"),
path('med-admin/<int:pk>/messageedit/',
         AdminMessageUpdateView.as_view(), name="adminmessageupdate"),
path('med-admin/<int:pk>messagedelete/',
         AdminMessageDeleteView.as_view(), name="adminmessagedelete"),
	]

tourandtravelapp/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import *


class SigninForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your username...'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'placeholder': 'Enter your password...'
    }))


   
class OfferForm(forms.ModelForm):
    class Meta:
        model = Offer
        fields = ["title", "offer_starts", "offer_ends",
                  "packages", "details", "cost", "image"]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter title...'
            }),
            'offer_starts': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'offer_ends': forms.DateInput(attrs={
                'class': 'form-control',
            }),
            'packages': forms.SelectMultiple(attrs={
                'class': 'myselect2',
            }),
            'details': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter details...'
            }),
            'cost': forms.NumberInput(attrs={
                "class": 'form-control',
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
        }

class ServicePackageForm(forms.ModelForm):
    class Meta:
        model = ServicePackage
        fields = ["title", "service", "rate", "duration", "details", "image"]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter title...'
            }),
            'service': forms.Select(attrs={
                'class': 'form-control',
            }),
            'rate': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'duration': forms.NumberInput(attrs={
                "class": 'form-control',
            }),
            'details': forms.TextInput(attrs={
                "class": 'form-control',
            }),
            # 'details': SummernoteWidget(),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "comment", ]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Your Fullname...',
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Your email address...'
            }),
            'comment': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your comment...'
            }),

        }


class PackageBookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        exclude = ["package"]
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your name...'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter email...'
            }),
            'address': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your address...'
            }),
            'date': forms.DateInput(attrs={
                'class': 'form-control datepicker',
                'type': 'date',
                'placeholder': 'Date'
            }),
            'adults': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'kids': forms.NumberInput(attrs={
                'class': 'form-control',
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your message...'
            }),
        }
class EnqueryForm(forms.ModelForm):
    package = forms.ModelChoiceField(
        widget=forms.Select(attrs={
            'class': 'form-control',
        }), queryset=ServicePackage.objects.none())

    class Meta:
        model = Enquery
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your name...'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter email...'
            }),
            'mobile': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter mobile...'
            }),
            'service': forms.Select(attrs={
                'class': 'form-control',
            }),
            'package': forms.Select(attrs={
                'class': 'form-control',
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your message...'
            }),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # print(self.data)
        if 'service' in self.data:
            service_obj = self.data.get('service')
            self.fields['package'].queryset = ServicePackage.objects.filter(
                service=service_obj)

class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = "__all__"
        widgets = {
            'sender': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter sender name...'
            }),
            'mobile': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter mobile...'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter email...'
            }),
            'subject': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your subject...'
            }),
            'message': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your message...'
            }),
        }

class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = "__all__"
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter title...'
            }),
            'slug': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter slug...'
            }),
            'images': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'icon': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter icon...'
            }),
             'content': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter content..'
            }),
        }

class SubscriberForm(forms.ModelForm):
    class Meta:
        model = Subscriber
        fields = "__all__"
        widgets = {
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter email...'
            }),
        }

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter name...'
            }),
            'post': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter post...'
            }),
            'image': forms.ClearableFileInput(attrs={
                'class': 'form-control'
            }),
            'mobile': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter mobile...'
            }),
            'email': forms.EmailInput(attrs={
                "class": 'form-control',
                'placeholder': 'Enter email'
            }),
            'detail': forms.Textarea(attrs={
                "class": 'form-control',
                'placeholder': 'Enter detail'
            }),
        }

class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = "__all__"
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter name...'
            }),
            'photo': forms.ClearableFileInput(attrs={
                'class': 'form-control',
            }),
            'sayings': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your words...'
            }),
            'profession': forms.TextInput(attrs={
                "class": 'form-control',
                'placeholder': 'Enter your profession...'
            }),
        }


class AlbumForm(forms.ModelForm):
    images = forms.FileField(widget=forms.FileInput(attrs={
        'multiple': True
    }))

    class Meta:
        model = Album
        fields = "__all__"
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Enter name...'
            }),
            'details': forms.Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'Enter your words...'
            }),
        }

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = "__all__"

templates/clienttemplate/ajaxgetpackages.html
<select>
{% for package in relatedpackages %}
<option value="{{package.id}}"> {{package.title}} </option>
{% endfor %}
</select>

templates/clienttemplate/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
<title>Tour and Travel | T&T</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta charset="utf-8">
<meta name="keywords" content="Grand Tour Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
	<!-- Smartsupp Live Chat script -->
<script type="text/javascript">
var _smartsupp = _smartsupp || {};
_smartsupp.key = 'cab33ea36ba9c44815b31cc8196f111c2da71d41';
window.smartsupp||(function(d) {
  var s,c,o=smartsupp=function(){ o._.push(arguments)};o._=[];
  s=d.getElementsByTagName('script')[0];c=d.createElement('script');
  c.type='text/javascript';c.charset='utf-8';c.async=true;
  c.src='https://www.smartsuppchat.com/loader.js?';s.parentNode.insertBefore(c,s);
})(document);
</script>
	<!-- css files -->
    <link href="{% static 'clientstatic/css/bootstrap.css' %}" rel='stylesheet' type='text/css' /><!-- bootstrap css -->
    <link href="{% static 'clientstatic/css/style.css' %}" rel='stylesheet' type='text/css' /><!-- custom css -->
    <link href="{% static 'clientstatic/css/font-awesome.min.css' %}" rel="stylesheet"><!-- fontawesome css -->
	<!-- //css files -->
	
	<link href="{% static 'clientstatic/css/css_slider.css' %}" type="text/css" rel="stylesheet" media="all">

	<!-- google fonts -->
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
	<!-- //google fonts -->
  {% block css%}

  {% endblock %}
<body>

<!-- header -->
<header>
	<div class="container">
		<!-- nav -->
		<nav class="py-md-4 py-3 d-lg-flex">
			<div id="logo">
				<h1 class="mt-md-0 mt-2"> <a href="{% url 'tourandtravelapp:home' %}"><span class="fa fa-map-signs"></span> {{organization.name}} </a></h1>
			</div>
			<label for="drop" class="toggle"><span class="fa fa-bars"></span></label>
			<input type="checkbox" id="drop" />
			<ul class="menu ml-auto mt-1">
        <li class="{% block home %} {% endblock %}"><a href="{% url 'tourandtravelapp:home' %}">Home</a></li>
        <li class="{% block about %} {% endblock %}"><a href="{% url 'tourandtravelapp:about' %}">About Us</a></li>
        <li class="{% block service %} {% endblock %}"><a href="{% url 'tourandtravelapp:service' %}">Services</a></li>
        <li class="{% block package %} {% endblock %}"><a href="{% url 'tourandtravelapp:package' %}">Packages</a></li>
        <li class="{% block contact %} {% endblock %}"><a href="{% url 'tourandtravelapp:contact' %}">Contact</a></li>


			
			<li class="booking"><a href="{% url 'tourandtravelapp:enquery' %}">Enquery</a></li>
			</ul>
		</nav>
		<!-- //nav -->
	</div>
</header>
<!-- //header -->
<!--Start of Tawk.to Script-->
<script type="text/javascript">
var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
(function(){
var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
s1.async=true;
s1.src='https://embed.tawk.to/5f86bad0a2eb1124c0bcc9e7/default';
s1.charset='UTF-8';
s1.setAttribute('crossorigin','*');
s0.parentNode.insertBefore(s1,s0);
})();
</script>
<!--End of Tawk.to Script-->

	{% if messages %}
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Successfull</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        {% for message in messages %}
          <p>{{message}}</p>
          {% endfor %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endif %}



{% block content %}
{% endblock %}





<!--footer -->
<footer>
<section class="footer footer_w3layouts_section_1its py-5">
	<div class="container py-lg-4 py-3">
		<div class="row footer-top">
			<div class="col-lg-3 col-sm-6 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>{{organization.address}}</h3>
				</div>
				<div class="footer-text">
					<p>Location : {{organization.address}}</p>
					<p>Phone : +12 534894364</p>
					<p>Email :{{organization.email}}</p>
					<p>Phone : {{organization.phone}}</p>
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 footer-grid_section mt-sm-0 mt-4">
				<div class="footer-title">
					<h3>About Us</h3>
				</div>
				<div class="footer-text">
					<p>{{organization.mission_and_vision}}.</p>
				</div>
				<ul class="social_section_1info">
					<li class="mb-2 facebook"><a href="#"><span class="fa fa-facebook"></span></a></li>
					<li class="mb-2 twitter"><a href="#"><span class="fa fa-twitter"></span></a></li>
					<li class="google"><a href="#"><span class="fa fa-google-plus"></span></a></li>
					<li class="linkedin"><a href="#"><span class="fa fa-linkedin"></span></a></li>
				</ul>
			</div>
			<div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>Travel Places</h3>
				</div>
				<div class="row">
		{% for destination in alldestination %}

					<ul class="col-6 links">
						<li><a href="{% url 'tourandtravelapp:servicedetail' destination.slug %}" class="scroll">{{destination.title}}</a></li>
						
					</ul>
					{% endfor %}
					
				</div>
			</div>
			<div class="col-lg-3 col-sm-6 mt-lg-0 mt-4 footer-grid_section_1its_w3">
				<div class="footer-title">
					<h3>Newsletter</h3>
				</div>
				<div class="footer-text">
					<p>By subscribing to our mailing list you will always get latest news and updates from us.</p>
					 <form action="{% url 'tourandtravelapp:subscriber' %}" method="post">
            {% csrf_token %}
            {{subsform.email}}
            <!-- <input type="email" name="Email" placeholder="Enter your email..." required=""> -->
            <button class="btn1"><i class="fa fa-paper-plane" aria-hidden="true"></i></button>
           <div class="clearfix"> </div>
          </form>
				</div>
			</div>
		</div>
	</div>
</section>
</footer>
<!-- //footer -->

<!-- copyright -->
<div class="copyright py-3 text-center">
	<p>© 2020 {{organization.name}}. All Rights Reserved | Design by {{organization.name}}</p>
</div>
<!-- //copyright -->

<!-- move top -->
<div class="move-top text-right">
	<a href="#home" class="move-top"> 
		<span class="fa fa-angle-up  mb-3" aria-hidden="true"></span>
	</a>
</div>
<!-- move top -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript" src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
<script type="text/javascript">
    $(window).on('load',function(){
        $('#myModal').modal('show');
    });
</script>

{% block js %}

{% endblock %}

</body>
</html>

templates/clienttemplate/service.html
{% extends "clienttemplate/base.html" %}

{% load static %}
{% block service %} active{% endblock %}
{% block content %}

<!-- banner -->
<section class="banner_inner" id="home">
	<div class="banner_inner_overlay">
	</div>
</section>
<!-- //banner -->
<div class="breadcrumb-w3pvt">
		<ol class="breadcrumb mb-0 text-center">
			<li class="breadcrumb-item">
				<a href="{% url 'tourandtravelapp:home' %}">Home</a>
			</li>
			<li class="breadcrumb-item active" aria-current="page">Service</li>
		</ol>
	</div>

<!-- services -->
<section class="services pt-5">
	<div class="container py-lg-5 py-sm-3">
		<h2 class="heading text-capitalize text-center mb-lg-5 mb-4"> Our Services</h2>
		<div class="row">
			<div class="col-lg-3 main-title-text">
				<h4 class="my-lg-4 mb-4">The journey of a thousand miles begins with a single step.</h4>
				<img src="{% static 'clientstatic/imagesp1.jpg' %}" alt="" class="img-fluid" />
			</div>
			<div class="col-lg-9 mt-lg-0 mt-5">
				<div class="row">
				{% for service in allservices %}
					<div class="col-lg-4 col-md-6 col-sm-6 service-grid-wthree text-center mb-5">
						<div class="ser-fashion-grid">
							<div class="about-icon mb-md-4 mb-3">
								<span class="fa {{service.icon}}" aria-hidden="true"></span>
							</div>
							<div class="ser-sevice-grid">
							  <h4 class="pb-3"><a href="{% url 'tourandtravelapp:servicedetail' service.slug %}">{{service.title}}</h4>
							  <p>{{service.content|striptags|truncatechars:"20"}}</p>
							</div>
					  </div>
					</div>
				{% endfor %}
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //services -->

<!-- text -->
<section class="text-content">
	<div class="overlay-inner py-5">
		<div class="container py-md-3">
			<div class="test-info">
				<h4 class="tittle">Enjoy The Trip</h4>
				<p class="mt-3">{{organization.mission_and_vision}}</p>
			
					     <a href="{% url 'tourandtravelapp:about' %}">About Us</a>
						<a href="{% url 'tourandtravelapp:enquery' %}">Enquery</a>
				
			</div>
		</div>
	</div>
</section>
<!-- //text -->


<!-- places -->
<section class="trav-grids py-5" id="desti">
	<div class="container py-xl-5 py-lg-3">
		<h3 class="heading text-capitalize text-center mb-lg-5 mb-4">Our Team</h3>
		<div class="row">
				{% for team in allteam %}
			<div class="col-lg-6 mt-4">
				<div class="grids-tem-one">
					<div class="row">
						<div class="col-sm-5 grids-img-left">
							<img src="{{team.image.url}}" alt="" class="img-fluid" >
						</div>
						<div class="col-sm-7 right-cont">
							<h4 class="mb-2 let mt-sm-0 mt-2 tm-clr">{{team.name}}</h4>
							<p class="mt-3"><strong>Post</strong> :{{team.post}}</p>
							<p class="mt-3"><strong>Mobile</strong> :{{team.mobile}}</p>
							<p class="mt-3"><strong>Email</strong> :{{team.email}}</p>
							<p class="mt-3"><strong>Detail</strong> :{{team.detail}}</p>
							<p class="duration mt-2"><span class="fa fa-clock-o mr-2"></span><strong>Experience</strong> : {{team.experience}}</p>
						</div>
					</div>
				</div>
			</div>	
				{% endfor %}
		</div>
	</div>
</section>
<!-- //places -->

{% endblock %}