tourandtravel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('django-admin/', admin.site.urls),
    path("",include("tourandtravelapp.urls")),
    path('summernote/', include('django_summernote.urls')),
    
]
 
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tourandtravelapp/urls.py
from django.urls import path
from .views import *

app_name="tourandtravelapp"
urlpatterns = [
# for client urls
	path("",HomeView.as_view(),name="home"),
    path('about/', AboutView.as_view(), name='about'),
    path('service/', ServiceView.as_view(), name='service'),
    path('package/', PackageView.as_view(), name='package'),
    path('contact/', ContactView.as_view(), name='contact'),
    path("subscriber/", SubscriberCreateView.as_view(), name="subscriber"),
    path('package/', PackageView.as_view(), name='package'),
	path('offer/<int:pk>/detail/',
		OfferDetailView.as_view(), name="offerdetail"),
	path('package/<int:pk>/detail/',
         PackageDetailView.as_view(), name="packagedetail"),
	path("service-package/<int:pk>/book/",
         ClientPackageBookView.as_view(), name='clientpackagebook'),
	path('enquery/', EnqueryView.as_view(), name='enquery'),
	path("ajax/service-packages/",
		AjaxGetPackagesView.as_view(), name='ajaxgetpackages'),
	path('package/<int:pk>/comment/',
         PackageCommentView.as_view(), name="packagecomment"),
	path('album/', AlbumView.as_view(), name='album'),
	path('service/<slug:slug>/detail/',
         ServiceDetailView.as_view(), name="servicedetail"),

	# foradmin
	path('signin/', SigninView.as_view(), name='signin'),
    path('signout/', SignoutView.as_view(), name='signout'),
    path('med-admin/home', AdminHomeView.as_view(), name='adminhome'),

    # for adding destination,delete update
    path('med-admin/service/list/',
    	AdminServiceListView.as_view(), name="adminservicelist"),
	path('med-admin/service/create/',
         AdminServiceCreateView.as_view(), name="adminservicecreate"),
	path('med-admin/<int:pk>/edit/',
         AdminServiceUpdateView.as_view(), name="adminserviceupdate"),
    path('med-admin/<int:pk>/delete/',
         AdminServiceDeleteView.as_view(), name="adminservicedelete"),

# forservice package
path('med-admin/servicepackage/list/',
         AdminServicePackageListView.as_view(), name="adminservicepackagelist"),
path('med-admin/servicepackage/create/',
         AdminServicePackageCreateView.as_view(), name="adminservicepackagecreate"),
path('med-admin/<int:pk>/packageedit/',
         AdminServicePackageUpdateView.as_view(), name="adminservicepackageupdate"),
path('med-admin/<int:pk>/packagedelete/',
         AdminServicePackageDeleteView.as_view(), name="adminservicepackagedelete"),

# for team
path('med-admin/team/list/',
         AdminTeamListView.as_view(), name="adminteamlist"),
path('med-admin/team/create/',
         AdminTeamCreateView.as_view(), name="adminteamcreate"),
path('med-admin/<int:pk>/teamedit/',
         AdminTeamUpdateView.as_view(), name="adminteamupdate"),
path('med-admin/<int:pk>/teamdelete/',
         AdminTeamDeleteView.as_view(), name="adminteamdelete"),

# for offer
path('med-admin/offer/list/',
         AdminOfferListView.as_view(), name="adminofferlist"),
path('med-admin/offer/create/',
         AdminOfferCreateView.as_view(), name="adminoffercreate"),
path('med-admin/<int:pk>/offeredit/',
         AdminOfferUpdateView.as_view(), name="adminofferupdate"),
path('med-admin/<int:pk>/offerdelete/',
         AdminOfferDeleteView.as_view(), name="adminofferdelete"),

# for subscriber
path('med-admin/subscriber/list/',
         AdminSubscriberListView.as_view(), name="adminsubscriberlist"),
path('med-admin/subscriber/create/',
         AdminSubscriberCreateView.as_view(), name="adminsubscribercreate"),
path('med-admin/<int:pk>/subscriberedit/',
         AdminSubscriberUpdateView.as_view(), name="adminsubscriberupdate"),
path('med-admin/<int:pk>/subscriberdelete/',
         AdminSubscriberDeleteView.as_view(), name="adminsubscriberdelete"),

# for testimonial
path('med-admin/testimonial/list/',
         AdminTestimonialListView.as_view(), name="admintestimoniallist"),
    path('med-admin/testimonial/create/',
         AdminTestimonialCreateView.as_view(), name="admintestimonialcreate"),
    path('med-admin/<int:pk>/testimonialedit/',
         AdminTestimonialUpdateView.as_view(), name="admintestimonialupdate"),
    path('med-admin/<int:pk>testimonialdelete/',
         AdminTestimonialDeleteView.as_view(), name="admintestimonialdelete"),

# for album
path('med-admin/album/list/',
         AdminAlbumListView.as_view(), name="adminalbumlist"),
path('med-admin/album/create/',
         AdminAlbumCreateView.as_view(), name="adminalbumcreate"),
path('med-admin/<int:pk>/albumedit/',
         AdminAlbumUpdateView.as_view(), name="adminalbumupdate"),
path('med-admin/<int:pk>albumdelete/',
         AdminAlbumDeleteView.as_view(), name="adminalbumdelete"),       

         # for image

path('med-admin/image/list/',
         AdminImageListView.as_view(), name="adminimagelist"),
path('med-admin/image/create/',
         AdminImageCreateView.as_view(), name="adminimagecreate"),
path('med-admin/<int:pk>/imageedit/',
         AdminImageUpdateView.as_view(), name="adminimageupdate"),
path('med-admin/<int:pk>imagedelete/',
         AdminImageDeleteView.as_view(), name="adminimagedelete"), 

# for video
path('med-admin/video/list/',
         AdminVideoListView.as_view(), name="adminvideolist"),
path('med-admin/video/create/',
         AdminVideoCreateView.as_view(), name="adminvideocreate"),
path('med-admin/<int:pk>/videoedit/',
         AdminVideoUpdateView.as_view(), name="adminvideoupdate"),
path('med-admin/<int:pk>videodelete/',
         AdminVideoDeleteView.as_view(), name="adminvideodelete"),
# for enqury
path('med-admin/enquery/list/',
         AdminEnqueryListView.as_view(), name="adminenquerylist"),
path('med-admin/enquery/create/',
         AdminEnqueryCreateView.as_view(), name="adminenquerycreate"),
path('med-admin/<int:pk>/enqueryedit/',
         AdminEnqueryUpdateView.as_view(), name="adminenqueryupdate"),
path('med-admin/<int:pk>enquerydelete/',
         AdminEnqueryDeleteView.as_view(), name="adminenquerydelete"),

# formessage
path('med-admin/message/list/',
         AdminMessageListView.as_view(), name="adminmessagelist"),
path('med-admin/message/create/',
         AdminMessageCreateView.as_view(), name="adminmessagecreate"),
path('med-admin/<int:pk>/messageedit/',
         AdminMessageUpdateView.as_view(), name="adminmessageupdate"),
path('med-admin/<int:pk>messagedelete/',
         AdminMessageDeleteView.as_view(), name="adminmessagedelete"),
	]

tourandtravelapp/models.py
from django.contrib.auth.models import User
from django.db import models


class TimeStamp(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    active = models.BooleanField(default=True)

    class Meta:
        abstract = True


class Organization(TimeStamp):
    name = models.CharField(max_length=200)
    logo = models.ImageField(upload_to="logo")
    email = models.EmailField()
    phone = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200, null=True, blank=True)
    address = models.CharField(max_length=200)
    slogan = models.CharField(max_length=200, null=True, blank=True)
    about = models.TextField()
    mission_and_vision = models.TextField()
    profile_image = models.ImageField(upload_to="profile")
    website = models.CharField(max_length=200)
    map_location = models.CharField(max_length=200)
    favicon = models.ImageField(upload_to="favicon", null=True, blank=True)
    facebook = models.CharField(max_length=200, null=True, blank=True)
    youtube = models.CharField(max_length=200, null=True, blank=True)
    instagram = models.CharField(max_length=200, null=True, blank=True)
    customer_served = models.ImageField(
        upload_to="customer_served", null=True, blank=True)
    awards = models.ImageField(upload_to="awards", null=True, blank=True)
    estb_date = models.DateField()

    def __str__(self):
        return self.name


class Service(TimeStamp):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    images = models.ImageField(upload_to="images")
    icon = models.CharField(max_length=50)
    content = models.TextField()

    def __str__(self):
        return self.title


class ServicePackage(TimeStamp):
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    rate = models.DecimalField(max_digits=19, decimal_places=2)
    duration = models.PositiveIntegerField()
    details = models.TextField()
    image = models.ImageField(upload_to="image")

    def __str__(self):
        return self.title


class Booking(TimeStamp):
    package = models.ForeignKey(ServicePackage, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=200)
    date = models.DateField()
    adults = models.PositiveIntegerField(default=1)
    kids = models.PositiveIntegerField(default=0)
    message = models.TextField()

    def __str__(self):
        return self.name + "(" + self.package.title + ")"


class Comment(TimeStamp):
    package = models.ForeignKey(ServicePackage, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    email = models.EmailField()
    comment = models.TextField()

    def __str__(self):
        return self.name + "(" + self.package.title + ")"


class Offer(TimeStamp):
    title = models.CharField(max_length=200)
    offer_starts = models.DateField()
    offer_ends = models.DateField()
    packages = models.ManyToManyField(ServicePackage)
    details = models.TextField()
    cost = models.DecimalField(max_digits=19, decimal_places=2)
    image = models.ImageField(upload_to="offerimage")

    def __str__(self):
        return self.title


class Team(TimeStamp):
    name = models.CharField(max_length=200)
    post = models.CharField(max_length=200)
    image = models.ImageField(upload_to="image")
    mobile = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    experience = models.PositiveIntegerField(null=True, blank=True)
    detail = models.TextField()

    def __str__(self):
        return self.name


class Subscriber(TimeStamp):
    email = models.EmailField()

    def __str__(self):
        return self.email


class Testimonial(TimeStamp):
    name = models.CharField(max_length=200)
    photo = models.ImageField(upload_to="photo")
    sayings = models.TextField()
    profession = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Album(TimeStamp):
    title = models.CharField(max_length=200)
    details = models.TextField()

    def __str__(self):
        return self.title


class Image(TimeStamp):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="image")
    caption = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.caption


class Video(TimeStamp):
    title = models.CharField(max_length=200)
    link = models.CharField(max_length=300)
    description = models.TextField()

    def __str__(self):
        return self.title


class Enquery(TimeStamp):
    name = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    mobile = models.CharField(max_length=200)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    package = models.ForeignKey(
        ServicePackage, on_delete=models.CASCADE, null=True, blank=True)
    message = models.TextField()

    def __str__(self):
        return self.name


class Message(TimeStamp):
    sender = models.CharField(max_length=200)
    mobile = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.sender

templates/admintemplate/adminenquerydelete.html
{% extends 'admintemplate/adminbase.html' %}


{% block content %}
<h3>Enquery Delete</h3>
<form method="POST">
	{% csrf_token %}
<p>Are you sure you want to delete?</p>
<button class="btn btn-danger">Yes</button>
<a href="/med-admin/enquery/list/" class="btn btn-primary">No</a>

</form>

{% endblock %}

templates/admintemplate/adminenquerylist.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <!-- <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div> -->
                	<div class="col-md-2">
                		<!-- <a href="{% url 'tourandtravelapp:adminenquerycreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a> -->
                	</div>
               <!--  </div> -->
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Enquery</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Name</th>
                                <th scope="col">Message</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for enquery in adminenquerylist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{enquery.name}}</td>
                                <td>{{enquery.message}}</td>
                                <td>
                                	<!-- <a href="{% url 'tourandtravelapp:adminenqueryupdate' enquery.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a> -->
                                	<a href="{% url 'tourandtravelapp:adminenquerydelete' enquery.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplate/adminimagecreate.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Service Form</h2> -->
            <!--// main-heading -->

            <!-- Forms content -->
            <section class="forms-section">

              
                
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Image Form</h4>
                    <form action="." method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                        <!-- <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                {{form.title}}
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Slug</label>
                                {{form.slug}}
                                
                            </div>
                        </div> -->
                        
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </form>
                </div>
                <!--// Forms-3 -->
             
            </section>
{% endblock %}

templates/admintemplate/adminimagelist.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <!-- <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div> -->
                	<div class="col-md-2">
                		<a href="{% url 'tourandtravelapp:adminimagecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
               <!--  </div> -->
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Image</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Album</th>
                                <th scope="col">Caption</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for image in adminimagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{image.album}}</td>
                                <td>{{image.caption}}</td>
                                <td>
                                	<a href="{% url 'tourandtravelapp:adminimageupdate' image.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'tourandtravelapp:adminimagedelete' image.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplate/adminlogin.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Modernize an Admin Panel Category Bootstrap Responsive Web Template | Login :: w3layouts</title>
    <!-- Meta Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta name="keywords" content="Modernize Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template,
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, Sony Ericsson, Motorola web design" />
    <script>
        addEventListener("load", function () {
            setTimeout(hideURLbar, 0);
        }, false);

        function hideURLbar() {
            window.scrollTo(0, 1);
        }
    </script>
    <!-- //Meta Tags -->

    <!-- Style-sheets -->
    <!-- Bootstrap Css -->
    <link href="{% static 'adminstatic/css/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- Bootstrap Css -->
    <!-- Common Css -->
    <link href="{% static 'adminstatic/css/style.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!--// Common Css -->
    <!-- Fontawesome Css -->
    <link href="{% static 'adminstatic/css/fontawesome-all.css' %}" rel="stylesheet">
    <!--// Fontawesome Css -->
    <!--// Style-sheets -->

    <!--web-fonts-->
    <link href="//fonts.googleapis.com/css?family=Poiret+One" rel="stylesheet">
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
    <!--//web-fonts-->
</head>

<body>

    <div class="bg-page py-5">
        <div class="container">
            <!-- main-heading -->
            <h2 class="main-title-w3layouts mb-2 text-center text-white">Login</h2>
            <!--// main-heading -->
             
            <div class="form-body-w3-agile text-center w-lg-50 w-sm-75 w-100 mx-auto mt-5">
                <form method="post" action="{% url 'tourandtravelapp:signin' %}">
                     {% if error %}
    <li class="text-danger">{{error}}</li>
    {% endif %}
                    {% csrf_token %}

                    {{form.as_p}}
                    
                    <div class="d-sm-flex justify-content-between">
                        <div class="form-check col-md-6 text-sm-left text-center">
                            <input type="checkbox" class="form-check-input" id="exampleCheck1">
                            <label class="form-check-label" for="exampleCheck1">Remember me</label>
                        </div>
                        <div class="forgot col-md-6 text-sm-right text-center">
                            <a href="forgot.html">forgot password?</a>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary error-w3l-btn mt-sm-5 mt-3 px-4">Login</button>
                </form>
                <p class="paragraph-agileits-w3layouts mt-4">Don't have an account
                    <a href="register.html">Create an account</a>
                </p>
                <h1 class="paragraph-agileits-w3layouts mt-2">
                    <a href="{% url 'tourandtravelapp:home' %}">Back to Home</a>
                </h1>

            </div>

            <!-- Copyright -->
            <div class="copyright-w3layouts py-xl-3 py-2 mt-xl-5 mt-4 text-center">
                <p>© 2018 Modernize . All Rights Reserved | Design by
                    <a href="http://w3layouts.com/"> W3layouts </a>
                </p>
            </div>
            <!--// Copyright -->
        </div>
    </div>


    <!-- Required common Js -->
    <script src="{% static 'adminstatic/js/jquery-2.2.3.min.js' %}"></script>
    <!-- //Required common Js -->

    <!-- Js for bootstrap working-->
    <script src="{% static 'adminstatic/js/bootstrap.min.js' %}"></script>
    <!-- //Js for bootstrap working -->

</body>

</html>

templates/admintemplate/adminmessagelist.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <!-- <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div> -->
                	<div class="col-md-2">
                	<!-- 	<a href="{% url 'tourandtravelapp:adminmessagecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a> -->
                	</div>
               <!--  </div> -->
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Message</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Sender</th>
                                <th scope="col">Message</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for message in adminmessagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{message.sender}}</td>
                                <td>{{message.message}}</td>
                                <td>
                                <!-- 	<a href="{% url 'tourandtravelapp:adminmessageupdate' message.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a> -->
                                	<a href="{% url 'tourandtravelapp:adminmessagedelete' message.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}

templates/admintemplate/adminoffercreate.html
{% extends 'admintemplate/adminbase.html' %}


{% block css %}
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/css/select2.min.css" rel="stylesheet" />
<style type="text/css">
    .select2-search__field{
        width: 400px!important;

    }
    .select2-container--default{
        margin-top: 30px!important;
    }
</style>

{% endblock %}

{% block content %}
<!-- main-heading -->
            <!-- <h2 class="main-title-w3layouts mb-2 text-center">Service Form</h2> -->
            <!--// main-heading -->

            <!-- Forms content -->
            <section class="forms-section">

              
                
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">Offer Form</h4>
                    <form action="." method="POST" enctype="multipart/form-data">
                    	{% csrf_token %}
                    	{{form.as_p}}
                        <!-- <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="inputEmail4">Title</label>
                                {{form.title}}
                                
                            </div>
                            <div class="form-group col-md-6">
                                <label for="inputPassword4">Slug</label>
                                {{form.slug}}
                                
                            </div>
                        </div> -->
                        <br>
                        <button type="submit" class="btn btn-primary w-50">Submit</button>
                    </form>
                </div>
                <!--// Forms-3 -->
             
            </section>
{% endblock %}

{% block js %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js"></script>


<script>
    $(document).ready(function() {
        $('#id_packages').select2({
            placeholder: "Select tour packages",
            allowClear: true,
        });
    });
</script>
{% endblock %}

templates/admintemplate/adminservicelist.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'tourandtravelapp:adminservicecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Destination</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Title</th>
                                <th scope="col">Image</th>
                                <th scope="col">Created at</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for service in adminservicelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{service.title}}</td>
                                <td><img src="{{service.images.url}}" width="70"></td>
                                <td>{{service.created_at}}</td>
                                <td>
                                	<a href="{% url 'tourandtravelapp:adminserviceupdate' service.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'tourandtravelapp:adminservicedelete' service.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>
        

{% endblock %}

templates/admintemplate/adminservicepackagelist.html
{% extends 'admintemplate/adminbase.html' %}

{% block content %}
<!-- <h2 class="main-title-w3layouts mb-2 text-center">Tables</h2> -->
            <!--// main-heading -->

            <!-- Tables content -->
                <div class="row">
                	<div class="col-md-10">
                		
		                
                	</div>
                	<div class="col-md-2">
                		<a href="{% url 'tourandtravelapp:adminservicepackagecreate' %}"  style="font-size: 40px"><span class="fas fa-plus-circle text-primary"></span></a>
                	</div>
                </div>
            <section class="tables-section">
                
                <!-- table5 -->
                <div class="outer-w3-agile mt-3">
                    <h4 class="tittle-w3-agileits mb-4">All Services Packages</h4>

                    <table class="table table-hover table-bordered">
                        <thead>
                            <tr>
                                <th scope="col">S.N</th>
                                <th scope="col">Title</th>
                                <th scope="col">Detail</th>
                                <th scope="col">Created at</th>
                                <th scope="col">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        	{% for servicepackage in adminservicepackagelist %}
                            <tr>
                                <th scope="row">{{forloop.counter}}</th>
                                <td>{{servicepackage.title}}</td>
                                <td>{{servicepackage.details|striptags|truncatechars:"30"}}</td>
                                <td>{{servicepackage.created_at}}</td>

                                <td>
                                	<a href="{% url 'tourandtravelapp:adminservicepackageupdate' servicepackage.id %}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                	<a href="{% url 'tourandtravelapp:adminservicepackagedelete' servicepackage.id %}" class="btn btn-danger"><i class="fas fa-trash"></i></a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
                <!--// table5 -->

            </section>

{% endblock %}